[package]
name = "gpu-driven-rendering"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
nalgebra = { workspace = true }
bytemuck = { workspace = true }

